# -*- coding: utf-8 -*-
"""final mll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RscWJek4zgDeDS1ThLAfrIYcU9qWYkfH
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("nhattruongdev/musan-noise")

print("Path to dataset files:", path)

!pip install librosa soundfile kagglehub tqdm

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pypiahmad/librispeech-asr-corpus")

print("Path to dataset files:", path)

import librosa
import numpy as np

def extract_features(clean, noisy, sr=16000, n_fft=512, hop_length=128):

    clean_stft = librosa.stft(clean, n_fft=n_fft, hop_length=hop_length)
    noisy_stft = librosa.stft(noisy, n_fft=n_fft, hop_length=hop_length)

    clean_mag = np.abs(clean_stft)
    noisy_mag = np.abs(noisy_stft)

    # Ideal Ratio Mask
    mask = clean_mag / (noisy_mag + 1e-8)
    mask = np.clip(mask, 0, 1)

    # Log magnitude as input
    log_noisy_mag = np.log1p(noisy_mag)

    return log_noisy_mag.T, mask.T

X = []
Y = []

for i in range(200):  # you can increase later
    clean = load_audio(random.choice(clean_files))
    noise = load_audio(random.choice(noise_files))

    snr = random.uniform(0, 10)
    noisy = mix_audio(clean, noise, snr)

    features, mask = extract_features(clean, noisy)

    min_len = min(len(features), len(mask))

    X.append(features[:min_len])
    Y.append(mask[:min_len])

X = np.vstack(X)
Y = np.vstack(Y)

print("X shape:", X.shape)
print("Y shape:", Y.shape)

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(257,)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(257, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss='mse'
)

model.summary()

history = model.fit(
    X, Y,
    epochs=15,
    batch_size=64,
    validation_split=0.1,
    verbose=1
)

def enhance_audio(model, noisy, sr=16000, n_fft=512, hop_length=128):

    noisy_stft = librosa.stft(noisy, n_fft=n_fft, hop_length=hop_length)
    noisy_mag = np.abs(noisy_stft)
    noisy_phase = np.angle(noisy_stft)

    log_noisy_mag = np.log1p(noisy_mag).T

    predicted_mask = model.predict(log_noisy_mag, verbose=0)

    enhanced_mag = noisy_mag * predicted_mask.T

    enhanced_stft = enhanced_mag * np.exp(1j * noisy_phase)
    enhanced_audio = librosa.istft(enhanced_stft, hop_length=hop_length)

    # Normalize safely
    enhanced_audio = enhanced_audio / (np.max(np.abs(enhanced_audio)) + 1e-8)

    return enhanced_audio

test_clean = load_audio(random.choice(clean_files))
test_noise = load_audio(random.choice(noise_files))

test_noisy = mix_audio(test_clean, test_noise, 5)

enhanced = enhance_audio(model, test_noisy)

import soundfile as sf
sf.write("noisy.wav", test_noisy, 16000)
sf.write("enhanced.wav", enhanced, 16000)

