# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeIKLzzPCQy6HD1z0_rI46AOABsU78Qv
"""

!pip install librosa soundfile numpy pandas matplotlib scikit-learn tensorflow kaggle

import librosa
import numpy as np
import os
import random
import zipfile
import matplotlib.pyplot as plt

zip_files = ["archive (1).zip", "archive (2).zip"]

for z in zip_files:
    with zipfile.ZipFile(z, 'r') as zip_ref:
        zip_ref.extractall("/content/data")

print("Extraction Done ✅")

for root, dirs, files in os.walk("/content/data"):
    print(root)

TIMIT_PATH = "/content/data/timit/timit"   # change if needed
NOISE_PATH = "/content/data"         # change if needed

def load_audio(file_path):
    audio, sr = librosa.load(file_path, sr=16000)
    return audio, sr

def extract_features(audio, sr):
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
    return mfcc.T

def add_noise(clean, noise, snr=10):
    clean_power = np.mean(clean**2)
    noise_power = np.mean(noise**2)

    factor = np.sqrt(clean_power / (10**(snr/10) * noise_power))
    noisy = clean + factor * noise
    return noisy

noise_files = []

for root, dirs, files in os.walk(NOISE_PATH):
    for f in files:
        if f.endswith(".wav"):
            noise_files.append(os.path.join(root, f))

print("Total noise files:", len(noise_files))

X = []
y = []

MAX_FILES = 200  # limit to avoid crash
count = 0

for root, dirs, files in os.walk(TIMIT_PATH):
    for file in files:
        if file.endswith(".wav"):

            if count >= MAX_FILES:
                break

            clean_path = os.path.join(root, file)
            clean_audio, sr = load_audio(clean_path)

            noise_path = random.choice(noise_files)
            noise_audio, _ = load_audio(noise_path)

            # match length
            min_len = min(len(clean_audio), len(noise_audio))
            clean_audio = clean_audio[:min_len]
            noise_audio = noise_audio[:min_len]

            noisy_audio = add_noise(clean_audio, noise_audio)

            mfcc_clean = extract_features(clean_audio, sr)
            mfcc_noisy = extract_features(noisy_audio, sr)

            X.append(mfcc_noisy)
            y.append(mfcc_clean)

            count += 1

# Find the maximum sequence length for padding
max_seq_len = 0
if X:
    max_seq_len = max(arr.shape[0] for arr in X)

# Pad sequences to the maximum length
X_padded = []
y_padded = []

for mfcc_noisy_arr, mfcc_clean_arr in zip(X, y):
    # Pad noisy features
    if mfcc_noisy_arr.shape[0] < max_seq_len:
        pad_width = ((0, max_seq_len - mfcc_noisy_arr.shape[0]), (0, 0))
        mfcc_noisy_arr = np.pad(mfcc_noisy_arr, pad_width, 'constant')
    X_padded.append(mfcc_noisy_arr)

    # Pad clean features
    if mfcc_clean_arr.shape[0] < max_seq_len:
        pad_width = ((0, max_seq_len - mfcc_clean_arr.shape[0]), (0, 0))
        mfcc_clean_arr = np.pad(mfcc_clean_arr, pad_width, 'constant')
    y_padded.append(mfcc_clean_arr)

X = np.array(X_padded)
y = np.array(y_padded)

print("Dataset shape:", X.shape, y.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, LSTM, Dense, Dropout

model = Sequential([
    Conv1D(64, 3, activation='relu', input_shape=(X.shape[1], X.shape[2]), padding='same'),
    Dropout(0.2),
    LSTM(128, return_sequences=True),
    Dense(64, activation='relu'),
    Dense(X.shape[2])
])

model.compile(optimizer='adam', loss='mse')
model.summary()

model.fit(X, y, epochs=10, batch_size=16, validation_split=0.1)

def enhance_audio(model, noisy_audio, sr):
    mfcc = extract_features(noisy_audio, sr)
    mfcc = np.expand_dims(mfcc, axis=0)
    enhanced = model.predict(mfcc)
    return enhanced

# test with any noise file
test_audio, sr = load_audio(noise_files[0])
enhanced = enhance_audio(model, test_audio, sr)

print("Enhanced shape:", enhanced.shape)

import librosa

def mfcc_to_audio(mfcc, sr=16000):
    mfcc = mfcc.T  # transpose back

    # Convert MFCC → Mel Spectrogram
    mel_spec = librosa.feature.inverse.mfcc_to_mel(mfcc)

    # Convert Mel → Audio
    audio = librosa.feature.inverse.mel_to_audio(mel_spec, sr=sr)

    return audio

from IPython.display import Audio

# take enhanced output
enhanced_mfcc = enhanced[0]

enhanced_audio = mfcc_to_audio(enhanced_mfcc)

# play audio
Audio(enhanced_audio, rate=16000)

print("Original Noisy Audio:")
Audio(test_audio, rate=16000)

print("Enhanced Audio:")
Audio(enhanced_audio, rate=16000)

import soundfile as sf

sf.write("enhanced_output.wav", enhanced_audio, 16000)

from google.colab import files
files.download("enhanced_output.wav")

# Helper function to get all WAV files in a directory and its subdirectories
def get_all_wav_files(base_path):
    wav_files = []
    for root, _, files in os.walk(base_path):
        for file in files:
            if file.endswith(".wav"):
                wav_files.append(os.path.join(root, file))
    return wav_files

# Get a list of all clean WAV files from TIMIT_PATH
all_timit_wav_files = get_all_wav_files(TIMIT_PATH)

if not all_timit_wav_files:
    print(f"Error: No WAV files found in {TIMIT_PATH}. Please check the path and data extraction.")
else:
    # Pick a random clean file
    clean_path = random.choice(all_timit_wav_files)
    clean_audio, sr = load_audio(clean_path)

    # Pick a random noise file
    noise_path = random.choice(noise_files)
    noise_audio, _ = load_audio(noise_path)

    # match length
    min_len = min(len(clean_audio), len(noise_audio))
    clean_audio = clean_audio[:min_len]
    noise_audio = noise_audio[:min_len]

    # create noisy input
    noisy_audio = add_noise(clean_audio, noise_audio)

    print(f"Selected clean audio from: {clean_path}")
    print(f"Selected noise audio from: {noise_path}")

    # enhance
    enhanced_mfcc = enhance_audio(model, noisy_audio, sr)[0]
    enhanced_audio = mfcc_to_audio(enhanced_mfcc)